[package]
name = "advent2018"
version = "0.1.0"
authors = ["Mike Mueller <mike@subfocal.net>"]

[dependencies]
argparse = ""
cached = ""
failure = ""
image = ""
itertools = ""
lazy_static = ""
rand = ""
regex = ""
