// GENERATED BY build.rs
// DO NOT EDIT BY HAND, CHANGES WILL BE LOST.
pub mod day01;

// Execute the solution for a particular day (1..25).
pub fn solve(day: usize) -> Result<(), Error> {
    let mut solver: Box<AdventSolver> = match day {
         1 => Box::new(day01::Solver::default()),
         _ => { return Err(format_err!("Invalid day number: {}", day)); }
    };
    solver.solve()
}
